name: build

on:
  pull_request:
  push:
  schedule:
    # at 08:00 on Sunday
    - cron: "0 8 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PG_BUILD_DIR: /home/runner/build
      PG_BUILD_PARALLELISM: 2
      PG_DATA_DIR: /home/runner/data
      PG_LOG_FILE: /home/runner/postgres.log

      # no underscores because this is a "magic" Postgres variable natively
      # understood by many Postgres utilities
      PGPORT: 5433

    steps:
      - uses: actions/checkout@v2
        with:
          repository: postgres/postgres

      - name: "./configure"
        run: ./configure --prefix $PG_BUILD_DIR

      - name: "make"
        run: make -j$PG_BUILD_PARALLELISM -s

      - name: "make install"
        run: make -j$PG_BUILD_PARALLELISM -s install

      - name: "Initialize data directory"
        run: $PG_BUILD_DIR/bin/initdb -D $PG_DATA_DIR

      - name: "Start Postgres"
        run: $PG_BUILD_DIR/bin/postgres -D $PG_DATA_DIR -p $PGPORT >$PG_LOG_FILE 2>&1 &

      - name: "Wait for Postgres"

        # We should probably get fancier here and try a psql every second for N
        # times so that we're not using as blunt of a tool as a sleep X.
        run: sleep 5

      - name: "Run tests (make installcheck-parallel)"
        run:  make installcheck-parallel
